### PR TITLE
add Lunabase to table

### PR DESCRIPTION
**Pull request by simondebbarma**
From their Notion: 

> We’re looking for past and future founders that aren’t settled on their next thing and want to work at [Luabase](https://www.notion.so/Work-at-Luabase-f853a0c546ab43fcaf7c85c6a64ee5a9) for 6 to 12 months while you sort out what’s next. We’ll need you for at least 20 hours a week.
> 
> If you want a safe place to build (and make some money!) while you plot your move (especially if you’re considering building in web3 or data) Luabase is the spot. [Get in touch](mailto:mike@luabase.com).

### CODE REVIEW

**Comment by mike-luabase** [comment]
Thanks @simondebbarma ! It's Luabase (not Lunabase). Would love to be added here!

**Comment by simondebbarma** [comment]
> Thanks @simondebbarma ! It's Luabase (not Lunabase). Would love to be added here!

@mike-luabase I am so sorry! I'm gonna ahead and blame this on kerning. Fixing, ASAP.

**Comment by mxstbr** [comment]
Would appreciate not reformatting the whole markdown, thank you!

**Comment by simondebbarma** [comment]
@mxstbr Ah, my extension must have done that without me noticing. I'll attempt getting it back to it's previous state.

**Comment by simondebbarma** [comment]
Fixed. This should reset the table to it's previous state.

**Review by mxstbr — APPROVED** [review]
Perfect! 👌 Thank you

**Pull request merged**
